image: atlassian/default-image:2

options:
  max-time: 30

definitions:
  caches:
    npm: $HOME/.npm

pipelines:
  branches:
    "{feature/**,release/**,hotfix/**}":
      - step:
          name: Apply infrastucture
          image: amazon/aws-cli
          script:
            # Install Terraform -> dev
            - echo Downloading Terraform executable
            - mkdir -p ~/bin
            - cd ~/bin
            - export PATH="$PATH:/root/bin"
            - yum install -y wget unzip curl
            - wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
            - echo Terraform was downloaded successfully.
            - unzip terraform_0.15.3_linux_amd64.zip

            # Collect the code of the branch
            - echo The branch complete name is ${BITBUCKET_BRANCH}
            - echo branch_name $BITBUCKET_BRANCH >> ${BITBUCKET_CLONE_DIR}/tempBranchNameFile
            - BRANCH_NAME=$(awk '{print $2}' $BITBUCKET_CLONE_DIR/tempBranchNameFile | cut -d'/' -f 2 | sed -e 's/[^A-Za-z0-9]//g' | tr '[:upper:]' '[:lower:]')
            - echo The parsed name is ${BRANCH_NAME}
            - BRANCH_NAME_LENGTH=${#BRANCH_NAME}
            - echo The total branch name cannot be more than 10 characters. The actual size is ${BRANCH_NAME_LENGTH} characters.
            - if [ $BRANCH_NAME_LENGTH -gt 10 ]; then exit 1; else echo The resources will be created with the name ${BRANCH_NAME}; fi

            # Provision Terraform resources
            - cd ${BITBUCKET_CLONE_DIR}/devops/terraform
            - echo Initializing Terraform
            - terraform init
            - echo Selecting the correct workspace
            - (terraform workspace new $BRANCH_NAME || true) && terraform workspace select $BRANCH_NAME

            # Ensure Terraform syntax is valid before proceeding.
            - echo Validating the template
            - terraform validate

            # Ensure this step passes so that the state is always pushed.
            - echo Applying the template on the $BRANCH_NAME environment
            - terraform apply -var-file=dev.tfvars -var="environment=${BRANCH_NAME}" -auto-approve
            - terraform output > ${BITBUCKET_CLONE_DIR}/outputs
            - echo branch_name $BRANCH_NAME >> ${BITBUCKET_CLONE_DIR}/outputs
            - cat ${BITBUCKET_CLONE_DIR}/outputs
          artifacts:
            - outputs
      - step:
          name: Run tests
          image: node:12.16.2
          caches:
            - npm
          script:
            # Install dependencies
            - echo Installing NPM dependencies
            - npm install
            - echo Dependencies installed successfully

            # Run tests
            - npm run test:ci
            - echo Tests were executed successfully
          artifacts:
            - outputs
      - step:
          image: greenberry/node-aws-cli
          name: Deploy
          script:
            # Install dependencies
            - echo Installing NPM dependencies
            - npm install

            # Deploy APIs
            - echo Deploy APIs
            - BRANCH_NAME=$(awk '/branch_name/ {print $2}' ${BITBUCKET_CLONE_DIR}/outputs)
            - ./node_modules/.bin/sls deploy -v -s ${BRANCH_NAME}
          artifacts:
            - outputs
    master:
      - step:
          name: Apply infrastucture on stage
          image: amazon/aws-cli
          script:
            # Install Terraform -> stage
            - echo Downloading Terraform executable
            - mkdir -p ~/bin
            - cd ~/bin
            - export PATH="$PATH:/root/bin"
            - yum install -y wget unzip curl
            - wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
            - echo Terraform was downloaded successfully.
            - unzip terraform_0.15.3_linux_amd64.zip

            #
            # Provision Terraform resources
            #
            - cd ${BITBUCKET_CLONE_DIR}/devops/terraform
            - echo Initializing Terraform
            - terraform init
            - echo Selecting the correct workspace
            - (terraform workspace new stage || true) && terraform workspace select stage

            # Ensure Terraform syntax is valid before proceeding.
            - echo Validating the template
            - terraform validate
            - echo Applying the template on the stage environment
            # Ensure this step passes so that the state is always pushed.
            - terraform apply -var-file=stage.tfvars -auto-approve
            - terraform output > ${BITBUCKET_CLONE_DIR}/outputs
            - cat ${BITBUCKET_CLONE_DIR}/outputs
          artifacts:
            - outputs
      - step:
          name: Run tests
          image: node:12.16.2
          caches:
            - npm
          script:
            # Install dependencies
            - echo Installing NPM dependencies
            - npm install
            - echo Dependencies installed successfully

            # Run tests
            - npm run test:ci
            - echo Tests were executed successfully
          artifacts:
            - ./**
            - outputs
      - step:
          image: greenberry/node-aws-cli
          name: Deploy
          script:
            # Install dependencies
            - echo Installing NPM dependencies
            - npm install

            # Deploy APIs
            - echo Deploy APIs
            - ./node_modules/.bin/sls deploy -v -s stage
          artifacts:
            - outputs
      - step:
          name: Apply infrastucture on prod stage
          image: amazon/aws-cli
          trigger: manual
          script:
            #
            # Install Terraform -> prod
            #
            - echo Downloading Terraform executable
            - mkdir -p ~/bin
            - cd ~/bin
            - export PATH="$PATH:/root/bin"
            - yum install -y wget unzip curl
            - wget https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
            - echo Terraform was downloaded successfully.
            - unzip terraform_0.15.3_linux_amd64.zip

            #
            # Provision Terraform resources
            #
            - cd ${BITBUCKET_CLONE_DIR}/devops/terraform
            - echo Initializing Terraform
            - terraform init
            - echo Selecting the correct workspace
            - (terraform workspace new prod || true) && terraform workspace select prod

            # Ensure Terraform syntax is valid before proceeding.
            - echo Validating the template
            - terraform validate

            # Apply on prod environment
            - echo Applying the template on the prod environment
            - terraform apply -var-file=prod.tfvars -auto-approve
            - terraform output > ${BITBUCKET_CLONE_DIR}/outputs
            - cat ${BITBUCKET_CLONE_DIR}/outputs
          artifacts:
            - outputs
      - step:
          name: Tag version
          script:
            - dt=$(date '+%Y-%m-%d_%H%M');
            - git tag release-${dt} ${BITBUCKET_COMMIT}
            - git tag -am "Tagging for release ${BITBUCKET_BUILD_NUMBER}" release-${dt}-${BITBUCKET_BUILD_NUMBER}
            - git push origin release-${dt}-${BITBUCKET_BUILD_NUMBER}
          artifacts:
            - outputs
      - step:
          image: greenberry/node-aws-cli
          name: Deploy
          script:
            # Install dependencies
            - echo Installing NPM dependencies
            - npm install

            # Deploy APIs
            - echo Deploy APIs
            - ./node_modules/.bin/sls deploy -v -s prod
          artifacts:
            - outputs
