version: "3"
services:
  api:
    container_name: api-container
    image: node:12.16.2-alpine
    working_dir: /usr/src/customer-api
    restart: always
    command: /bin/sh -c "yarn install && npm run debug -- --host 0.0.0.0"
    volumes:
      - ./package.json:/usr/src/customer-api/package.json
      - ./serverless.yml:/usr/src/customer-api/serverless.yml
      - ./webpack.config.js:/usr/src/customer-api/webpack.config.js
      - ./tsconfig.json:/usr/src/customer-api/tsconfig.json
      - ./tsconfig-build.json:/usr/src/customer-api/tsconfig-build.json
      - ./src:/usr/src/customer-api/src
    ports:
      - "3000:3000"
      - "9222:9222"