version: "3"
services:
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/customer-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/customer-api/dist/
      - ./package.json:/usr/src/customer-api/package.json
    ports:
      - "3000:3000"
      - "9222:9222"