service: customer-api

frameworkVersion: '2'

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-domain-manager

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    stage: dev
    memorySize: 128
    endpointType: regional
    timeout: 5
    deploymentBucket:
        blockPublicAccess: true
    iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'
package:
  individually: true

custom:
    stage: ${opt:stage, self:provider.stage}
    projectName: customer-api
    customDomain:
        domainName: ${opt:stage, self:provider.stage}-customer-api.pagaleve.me
        basePath: "v1"
        stage: ${opt:stage, self:provider.stage}
        certificateName: "pagaleve.me"
        certificateRegion: ${opt:stage, self:provider.region}
        createRoute53Record: true
    webpack:
        includeModules:
            forceExclude:
                - aws-sdk
    allowedHeaders:
        - Accept
        - Content-Type
        - Content-Length
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent

functions:
    saveCustomer:
        role: ${ssm:${self:custom.stage}-lambda-dynamodb-iam-role}
        handler: src/main/handlers/save-customer-handler.handler
        description: Create or update a customer
        events:
        - http:
            path: /customers
            method: PUT
            cors: true
            authorizer:
                name: authorizer
                arn: ${ssm:${self:custom.stage}-cognito-user-pool-arn}
        environment:
            STAGE: ${self:custom.stage}
            DYNAMODB_CUSTOMER_TABLE_NAME: ${ssm:${self:custom.stage}-${self:custom.projectName}-dynamodb-customer-name}
    loadCustomerById:
        role: ${ssm:${self:custom.stage}-lambda-dynamodb-iam-role}
        handler: src/main/handlers/load-customer-by-id-handler.handler
        description: Load a customer by id
        events:
        - http:
            path: /customers/{customerId}
            method: GET
            cors: true
            authorizer:
                name: authorizer
                arn: ${ssm:${self:custom.stage}-cognito-user-pool-arn}
        environment:
            DYNAMODB_CUSTOMER_TABLE_NAME: ${ssm:${self:custom.stage}-${self:custom.projectName}-dynamodb-customer-name}
    deleteCustomerById:
        role: ${ssm:${self:custom.stage}-lambda-dynamodb-iam-role}
        handler: src/main/handlers/delete-customer-by-id-handler.handler
        description: Delete a customer by id
        events:
        - http:
            path: /customers/{customerId}
            method: DELETE
            cors:
                origins:
                    - "*"
                headers: ${self:custom.allowedHeaders}
            authorizer:
                name: authorizer
                arn: ${ssm:${self:custom.stage}-cognito-user-pool-arn}
        environment:
            STAGE: ${self:custom.stage}
            DYNAMODB_CUSTOMER_TABLE_NAME: ${ssm:${self:custom.stage}-${self:custom.projectName}-dynamodb-customer-name}
    listCustomers:
        role: ${ssm:${self:custom.stage}-lambda-dynamodb-iam-role}
        handler: src/main/handlers/list-customers-handler.handler
        description: Load customers
        events:
        - http:
            path: /customers
            method: GET
            cors: true
            authorizer:
                name: authorizer
                arn: ${ssm:${self:custom.stage}-cognito-user-pool-arn}
        environment:
            DYNAMODB_CUSTOMER_TABLE_NAME: ${ssm:${self:custom.stage}-${self:custom.projectName}-dynamodb-customer-name}
    searchCustomers:
        role: ${ssm:${self:custom.stage}-lambda-basic-iam-role}
        handler: src/main/handlers/search-customers-handler.handler
        description: Search customers
        events:
        - http:
            path: /customers/search
            method: GET
            cors: true
            authorizer:
                name: authorizer
                arn: ${ssm:${self:custom.stage}-cognito-user-pool-arn}
        environment:
            STAGE: ${self:custom.stage}
            ALGOLIA_APP_ID: ${ssm:serverless-algolia-app-id}
            ALGOLIA_ADMIN_API_KEY: ${ssm:serverless-algolia-admin-api-key}
            ALGOLIA_INDEX_NAME: customer-api-${self:custom.stage}
    login:
        role: ${ssm:${self:custom.stage}-lambda-cognito-iam-role} 
        handler: src/main/handlers/extras/login-handler.handler
        events:
        - http:
            path: /login
            method: POST
            cors: true
        environment:
            COGNITO_USER_POOL_ID: ${ssm:${self:custom.stage}-cognito-user-pool-id}
            COGNITO_CLIENT_ID: ${ssm:${self:custom.stage}-cognito-user-client-id}
    updateAlgoliaIndex:
        handler: src/main/handlers/extras/update-algolia-index-handler.handler
        events:
        - stream:
            type: dynamodb
            batchSize: 1
            startingPosition: LATEST
            arn: ${ssm:${self:custom.stage}-${self:custom.projectName}-dynamodb-customer-stream-arn}
        environment:
            STAGE: ${self:custom.stage}
            ALGOLIA_APP_ID: ${ssm:serverless-algolia-app-id}
            ALGOLIA_ADMIN_API_KEY: ${ssm:serverless-algolia-admin-api-key}
            ALGOLIA_INDEX_NAME: customer-api-${self:custom.stage}