service: consumer-api

frameworkVersion: '2'

plugins:
    - serverless-webpack
    - serverless-offline

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    stage: dev
    memorySize: 128
    timeout: 5

package:
  individually: true

custom:
    stage: ${opt:stage, self:provider.stage}
    webpack:
        includeModules: true

functions:
    login:
        role: ${ssm:${self:custom.stage}-lambda-cognito-iam-role} 
        handler: src/main/routes/login.handler
        events:
        - http:
            path: /login
            method: POST
            cors: true
        environment:
            COGNITO_USER_POOL_ID: ${ssm:${self:custom.stage}-cognito-user-pool-id}
            COGNITO_CLIENT_ID: ${ssm:${self:custom.stage}-cognito-user-client-id}
    helloWorld:
        handler: src/main/routes/hello-world.handler
        description: Lambda function just test purpose
        events:
        - http:
            path: /hello
            method: GET
            cors: true
            authorizer:
                name: authorizer
                arn: ${ssm:${self:custom.stage}-cognito-user-pool-arn}