region                        = "us-east-1"
project_name                  = "customer-api"
environment                   = "stage"
admin_cognito_email           = "admin@pagaleve.com.br"
admin_cognito_password        = "o12E45"
admin_group_cognito_name      = "admin"